### ISSUE TITLE
「ブンより」provisioning.shファイルの実行およびDocker installについて

### ISSUE THREAD

**Issue by serraleone** [landwarrior/react_microservice_sample#1]
お疲れ様です。ブンです。

表題の件につきまして、

①provisioning.shファイルの実行のため、まずそのファイルの改行をLFに指定しないと、エラーが出てきます。
エラー：/usr/bin/env: ‘bash\r’: No such file or directory

②dockerのインストールに関して、
「yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo」を実行するには、
ROOT Userの権限が必要です。そのため、上記のコマンドの先頭に「sudo 」を付けさせていただきまして、
解決できました。

以上です。よろしくお願いいたします。

**Comment by landwarrior** [comment]
ご報告ありがとうございます。

provisioning.sh について、まずソースコードは clone でローカルに持っていきましたか？
その場合、 git の config が悪さをしているかもしれません。
（手元では改行コードは LF になっているように見えました）
コマンドプロンプトで以下のコマンドを実行してください。

```
git config --global core.autocrlf false
git config --global core.ignorecase false
```

Windows環境で git clone すると、文字コードが自動変換されて CRLF になってしまいます。
なので、 `core.autocrlf` を `false` に設定しておきます。
もう一つは、大文字と小文字を区別できるように設定します。
こちらの設定を入れてから、改めて git clone してみてください。

もう一つの `yum-config-manager` の件は、報告ありがとうございます。
修正しておきます。
